### ISSUE TITLE
Unable to find setuid files

### ISSUE THREAD

**Issue by looCiprian** [initstring/uptux#9]
Uptux **is not able** to find **setuid** files.
That type of checks can be very helpful for **privilege escalation**.

**Comment by initstring** [comment]
Hi @looCiprian ,

Thanks so much for taking the time to open an issue! Yes, I agree - finding setuid files is pretty important.

My goal with uptux, though, is not to replace the classic Linux privesc tools (unix-privesc-check, linuxprivchecker, linenum). There are TONS of basic privesc things that uptux does not check for. Instead, it is just a way for me to automate some of the more unique vectors I encounter while learning more about Linux myself.

I won't be adding basic checks in, but I do appreciate you opening the issue.

**Comment by looCiprian** [comment]
Thank you very much for the explanation! 
I understand your perspective.
